default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: freemarket_sample_0609b_development

test:
  <<: *default
  database: freemarket_sample_0609b_test

production:
  <<: *default
  database: freemarket_sample_0609b_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
